language: julia
os:
  - linux
julia:
  - 0.4
  - 0.5
  - 0.6
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("QuickHull")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("QuickHull")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # generate and push Documentation
  - julia -e 'cd(Pkg.dir("QuickHull")); Pkg.add("Documenter"); include(joinpath("docs","make.jl"))'
